<?php

namespace Victoire\Bundle\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Victoire\Bundle\CoreBundle\Entity\BaseEntityProxy;
// Generated by EntityProxyGenerator on CacheWarmup
use Victoire\Bundle\BlogBundle\Entity\Article;
use Victoire\Bundle\BlogBundle\Entity\Tag;
// END Generation

/**
 * EntityProxy
 * Generated by EntityProxyGenerator on CacheWarmup
 *
 * @ORM\Entity
 * @ORM\Table("vic_entity_proxy")
 */
class EntityProxy extends BaseEntityProxy
{

    protected $article;
    protected $tag;

    /**
     * @param Article $article
     *
     */
    public function setArticle(Article $article)
    {
        $this->article = $article;
    }

    /**
     * @return Article
     */
    public function getArticle()
    {
        return $this->article;
    }

    /**
     * @param Tag $tag
     *
     */
    public function setTag(Tag $tag)
    {
        $this->tag = $tag;
    }

    /**
     * @return Tag
     */
    public function getTag()
    {
        return $this->tag;
    }


}
