imports:
    - { resource: "@VictoireCoreBundle/Resources/config/config.yml" }
    - { resource: "@VictoireTwigBundle/Resources/config/config.yml" }

assetic:
    use_controller: false
    node: /usr/bin/node
    node_paths: [/usr/lib/node_modules]
    bundles: ~
    filters:
        cssrewrite: ~
        less: ~ #Victoire needs less under v3.0.0

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Victoire\Bundle\UserBundle\Entity\User
    from_email:
        address: hey@victoire.io
        sender_name: Victoire

snc_redis:
    clients:
        victoire:
            type: predis
            alias: victoire
            dsn: %victoire_redis_path%
            logging: false

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true

victoire_core:
    user_class: Victoire\Bundle\UserBundle\Entity\User
    business_entity_debug: true
    layouts:
        defaultLayout: "Default layout"

#if you need i18n
victoire_i18n:
    available_locales:
        - fr
        - en
    locale_pattern: parameter #domain
